--Place this file in your .xmonad/lib directory and import module Colors into .xmonad/xmonad.hs config
--The easy way is to create a soft link from this file to the file in .xmonad/lib using ln -s
--Then recompile and restart xmonad.

module Colors
    ( wallpaper
    , background, foreground, cursor
    , color0, color1, color2, color3, color4, color5, color6, color7
    , color8, color9, color10, color11, color12, color13, color14, color15
    ) where

-- Shell variables
-- Generated by 'wal'
wallpaper="/home/paulo/images/wallpapers/orthodox_woman.jpg"

-- Special
background="#0B0403"
foreground="#eee2a7"
cursor="#eee2a7"

-- Colors
color0="#0B0403"
color1="#C23808"
color2="#B14E06"
color3="#A65109"
color4="#CA6906"
color5="#E1A107"
color6="#EDCB18"
color7="#eee2a7"
color8="#a69e74"
color9="#C23808"
color10="#B14E06"
color11="#A65109"
color12="#CA6906"
color13="#E1A107"
color14="#EDCB18"
color15="#eee2a7"
