--Place this file in your .xmonad/lib directory and import module Colors into .xmonad/xmonad.hs config
--The easy way is to create a soft link from this file to the file in .xmonad/lib using ln -s
--Then recompile and restart xmonad.

module Colors
    ( wallpaper
    , background, foreground, cursor
    , color0, color1, color2, color3, color4, color5, color6, color7
    , color8, color9, color10, color11, color12, color13, color14, color15
    ) where

-- Shell variables
-- Generated by 'wal'
wallpaper="/home/paulo/images/wallpapers/japanese/geisha.jpg"

-- Special
background="#0e0f12"
foreground="#d8d5d5"
cursor="#d8d5d5"

-- Colors
color0="#0e0f12"
color1="#7E7F7F"
color2="#B74532"
color3="#C1935A"
color4="#5D748C"
color5="#708A98"
color6="#9C9A9F"
color7="#d8d5d5"
color8="#979595"
color9="#7E7F7F"
color10="#B74532"
color11="#C1935A"
color12="#5D748C"
color13="#708A98"
color14="#9C9A9F"
color15="#d8d5d5"
