--Place this file in your .xmonad/lib directory and import module Colors into .xmonad/xmonad.hs config
--The easy way is to create a soft link from this file to the file in .xmonad/lib using ln -s
--Then recompile and restart xmonad.

module Colors
    ( wallpaper
    , background, foreground, cursor
    , color0, color1, color2, color3, color4, color5, color6, color7
    , color8, color9, color10, color11, color12, color13, color14, color15
    ) where

-- Shell variables
-- Generated by 'wal'
wallpaper="/home/paulo/.config/wallpaper.jpg"

-- Special
background="#0D1212"
foreground="#e4e1ce"
cursor="#e4e1ce"

-- Colors
color0="#0D1212"
color1="#8B3933"
color2="#8B7258"
color3="#7B817E"
color4="#978D6C"
color5="#C9A374"
color6="#A0A099"
color7="#e4e1ce"
color8="#9f9d90"
color9="#8B3933"
color10="#8B7258"
color11="#7B817E"
color12="#978D6C"
color13="#C9A374"
color14="#A0A099"
color15="#e4e1ce"
